package com.sgm.doe.service.integrate.shipping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-12-20T09:55:46.085+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://shipping.integrate.service.doe.sgm.com/", name = "ShipmentService")
@XmlSeeAlso({ObjectFactory.class})
public interface ShipmentService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateShipmentInfo", targetNamespace = "http://shipping.integrate.service.doe.sgm.com/", className = "com.sgm.doe.service.integrate.shipping.UpdateShipmentInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateShipmentInfoResponse", targetNamespace = "http://shipping.integrate.service.doe.sgm.com/", className = "com.sgm.doe.service.integrate.shipping.UpdateShipmentInfoResponse")
    public String updateShipmentInfo(
        @WebParam(name = "ASNNumber", targetNamespace = "")
            String asnNumber,
        @WebParam(name = "DeliveryDate", targetNamespace = "")
            String deliveryDate
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getShipmentInfo", targetNamespace = "http://shipping.integrate.service.doe.sgm.com/", className = "com.sgm.doe.service.integrate.shipping.GetShipmentInfo")
    @WebMethod
    @ResponseWrapper(localName = "getShipmentInfoResponse", targetNamespace = "http://shipping.integrate.service.doe.sgm.com/", className = "com.sgm.doe.service.integrate.shipping.GetShipmentInfoResponse")
    public java.util.List<Shipment> getShipmentInfo(
        @WebParam(name = "ASNNumber", targetNamespace = "")
            String asnNumber
    );
}
